{% set name = "histogrammar" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/histogrammar-{{ version }}.tar.gz
  sha256: 3b47ed3a1336bbc6458d6b9680287621a2b3db4ac6607cb23e988e27cec0e8bc

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - joblib >=0.14.0
    - numpy >=1.18.0
    - python
    - tqdm

test:
  imports:
    - histogrammar
  commands:
    - pip check
  requires:
    - pip
    - pandas

about:
  home: https://histogrammar.github.io/histogrammar-docs
  summary: Composable histogram primitives for distributed data reduction.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mepa
