{% set name = "histogrammar" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/histogrammar-{{ version }}.tar.gz
  sha256: ffea5e62dc793a75188a2b5850bdeb963c305dd24d7a880669608bd4a15bf0ac

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - joblib >=0.14.0
    - numpy >=1.18.0
    - python
    - tqdm

test:
  imports:
    - histogrammar
  commands:
    - pip check
  requires:
    - pip
    - pandas

about:
  home: https://histogrammar.github.io/histogrammar-docs
  summary: Composable histogram primitives for distributed data reduction.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mepa
