{% set name = "histogrammar" %}
{% set version = "1.0.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/histogrammar-{{ version }}.tar.gz
  sha256: 3fd93646d568129637b6be0b98a6fab575eaf7426cb9f709a36908190cae85c5

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - joblib >=0.14.0
    - numpy >=1.18.0
    - python
    - tqdm

test:
  imports:
    - histogrammar
  commands:
    - pip check
  requires:
    - pip
    - pandas

about:
  home: https://histogrammar.github.io/histogrammar-docs
  summary: Composable histogram primitives for distributed data reduction.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mepa
